title: Gonçalo Moura # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! I have built this portfolio to showcase some of the skills i have aquired this past year. I have been working as a Data Scientist for a brand protection company, and some of my responsibilities included:<br>
  - Developing a Large Language Model to identify fairly used content.<br>
  - Creating online entity risk profiles with unsupervised learning.<br>
  - Constructing project APIs for seamless production integration.<br>
  If you want you can request me a Demo on a Specific use-case by sending me an email <br>
  {% include contact-form.html %}
  <br>
  <a href="https://www.linkedin.com/in/goncalo-j-moura/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-contact-form
google_analytics: G-WKN8DL6R9M # your Google Analytics tracking ID here
