title: Gonçalo Moura # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a Data Scientist with a strong background in Mathematics and Computer Science. I'm passionate about using AI and machine learning algorithms to uncover valuable insights from complex datasets. I also enjoy automating processes for efficient decision-making. My ultimate goal is to contribute to ambitious projects that strive to make an impact and drive meaningful change in the world.
  <br><br>
  <a href="https://www.linkedin.com/in/goncalo-j-moura/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-WKN8DL6R9M # your Google Analytics tracking ID here
